name: Transaction Management Build

on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches:
      - master
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Validate Gradle wrapper for security
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # Step 3: Set up JDK 17 with built-in Gradle caching
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17.0.11'
          distribution: 'temurin'
          cache: gradle

      # Step 4: Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      # Step 5: Build and test with Gradle
      - name: Build and test with Gradle
        run: ./gradlew build

      # Step 6: Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Application-JARs
          path: build/libs/
          retention-days: 7

